--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OutiServer/Mail
build-by-default: true
branches:
- master
projects:
  Mail:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
      - src: KenCir/Commando/Commando
        version: ^3.1.0
      - src: KenCir/FormAPI/libFormAPI
        version: ^2.1.0
...
