--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OutiServer/Mail
build-by-default: true
branches:
- master
projects:
  Mail:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: 4.1.0
      - src: KenCir/FormAPI/libFormAPI
        version: 1.1.0
...
