# データベースConfigのバージョン
version: 1.0.0

# データベースの設定
database:
  type: sqlite
  sqlite:
    file: mail.db
  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: your_schema
  worker-limit: 1